name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        name: Install Dependencies ${{ matrix.node-version }}
        with:
           node-version: ${{ matrix.node-version }}
           cache: "npm"
      - name: Install dependencies
        run: npm install

      - run: npx nx test common-ui
